/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.example.Monster;
import java.util.LinkedList;
import java.util.Random;

public class App {
  final static Random random = new Random();
  final static int maxRandomNumber = 4;// ランダムな数値の最大値(0～4)

  public String getGreeting() {
    return "Hello SEMonster";
  }

  public static void main(String[] args) {
    System.out.println(new App().getGreeting());
    SeMonsterGame mf = new SeMonsterGame(createRandomList(10));
    mf.addPlayer("user");
    mf.draw("user");

  }

}
