/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
  @Test
  public void testAppHasAGreeting() {
    App classUnderTest = new App();
    String name = App.getNameFromUser();
    assertEquals("TestName", name);
    assertEquals("Hello SEMonster", classUnderTest.getGreeting());
  }
}
